import { GoogleGenAI } from "@google/genai";
import { GenerationType } from "../types";

// Helper to strip the data:image/...;base64, prefix
const cleanBase64 = (dataUrl: string): string => {
  return dataUrl.split(',')[1] || dataUrl;
};

// Helper to determine mime type from data URL
const getMimeType = (dataUrl: string): string => {
  const match = dataUrl.match(/^data:(.+);base64,/);
  return match ? match[1] : 'image/png';
};

export const generateHairstyle = async (
  userImage: string,
  type: GenerationType,
  prompt?: string,
  refImage?: string
): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // We use gemini-2.5-flash-image for general image editing tasks
    const model = 'gemini-2.5-flash-image';
    
    const parts: any[] = [];

    // 1. Add User Image (The subject)
    parts.push({
      inlineData: {
        data: cleanBase64(userImage),
        mimeType: getMimeType(userImage)
      }
    });

    // 2. Add Instructions/Prompt based on type
    if (type === GenerationType.IMAGE && refImage) {
      // Add Reference Hairstyle Image
      parts.push({
        inlineData: {
          data: cleanBase64(refImage),
          mimeType: getMimeType(refImage)
        }
      });
      
      // Instruction to combine them
      parts.push({
        text: "Here are two images. The first image is the user (face). The second image is a reference hairstyle. Generate a photorealistic image of the person from the first image wearing the hairstyle from the second image. \n\nIMPORTANT RULES:\n1. Maintain the identity, facial features, and skin tone of the person in the first image EXACTLY.\n2. Apply the hairstyle from the second image naturally, matching the texture and color.\n3. Ensure high quality, photorealistic lighting and shadows."
      });
    } else {
      // Text description mode
      const styleDescription = prompt || "a modern, stylish haircut";
      parts.push({
        text: `Change the hairstyle of the person in this image to ${styleDescription}. \n\nIMPORTANT RULES:\n1. Maintain the identity, facial features, and skin tone of the person EXACTLY.\n2. Only change the hair.\n3. Ensure the new hair looks photorealistic and blends naturally with the head shape.`
      });
    }

    const response = await ai.models.generateContent({
      model: model,
      contents: { parts },
      // Note: responseMimeType is not supported for image models usually, but we check parts
    });

    // Extract image from response
    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
